/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resto_makanan;

/**
 *
 * @author Administrator
 */
public class fmenu extends javax.swing.JFrame {

    /**
     * Creates new form fmenu
     */
    public fmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_regis = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        fpegawai = new javax.swing.JMenuItem();
        fbarang = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        fpenjualan = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        flaporanstokbarang = new javax.swing.JMenuItem();
        flaporanpenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hai Selamat Bekerja, Semangat Pagi!");

        btn_regis.setText("Logout");
        btn_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regisActionPerformed(evt);
            }
        });

        master.setText("Master");

        fpegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        fpegawai.setText("Pegawai");
        fpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpegawaiActionPerformed(evt);
            }
        });
        master.add(fpegawai);

        fbarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        fbarang.setText("tambah makanan");
        fbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbarangActionPerformed(evt);
            }
        });
        master.add(fbarang);

        jMenuBar1.add(master);

        transaksi.setText("Transaksi");

        fpenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        fpenjualan.setText("Penjualan");
        fpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpenjualanActionPerformed(evt);
            }
        });
        transaksi.add(fpenjualan);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");

        flaporanstokbarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        flaporanstokbarang.setText("Laporan Penjualan makanan");
        flaporanstokbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flaporanstokbarangActionPerformed(evt);
            }
        });
        laporan.add(flaporanstokbarang);

        flaporanpenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        flaporanpenjualan.setText("laporan hitung jual");
        flaporanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flaporanpenjualanActionPerformed(evt);
            }
        });
        laporan.add(flaporanpenjualan);

        jMenuBar1.add(laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btn_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(btn_regis)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbarangActionPerformed
        // TODO add your handling code here:
        fmakan fb = new fmakan();
        fb.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_fbarangActionPerformed

    private void fpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpenjualanActionPerformed
        // TODO add your handling code here:
        fpenjualan ffp = new fpenjualan();
        ffp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fpenjualanActionPerformed

    private void flaporanstokbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flaporanstokbarangActionPerformed
        // TODO add your handling code here:
        flaporanhitung fls = new flaporanhitung();
        fls.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flaporanstokbarangActionPerformed

    private void fpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpegawaiActionPerformed
        // TODO add your handling code here:
        fpegawai fp = new fpegawai();
        fp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fpegawaiActionPerformed

    private void flaporanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flaporanpenjualanActionPerformed
        // TODO add your handling code here:
         flaporanmakanan flb = new flaporanmakanan();
        flb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flaporanpenjualanActionPerformed

    private void btn_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regisActionPerformed
        // TODO add your handling code here:
        fregis fb = new fregis();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                flogin fb = new flogin();
        fb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regis;
    private javax.swing.JMenuItem fbarang;
    private javax.swing.JMenuItem flaporanpenjualan;
    private javax.swing.JMenuItem flaporanstokbarang;
    private javax.swing.JMenuItem fpegawai;
    private javax.swing.JMenuItem fpenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenu master;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables

}
